# Generated by Django 4.2.9 on 2025-11-25 09:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Weight in kilograms",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20.0),
                            django.core.validators.MaxValueValidator(300.0),
                        ],
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True,
                        help_text="Height in centimeters",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100.0),
                            django.core.validators.MaxValueValidator(250.0),
                        ],
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Date of birth for age calculation",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="O",
                        help_text="Gender for TDEE calculation",
                        max_length=1,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (Little/No Exercise)"),
                            ("light", "Light Activity (1-3 days/week)"),
                            ("moderate", "Moderate (3-5 days/week)"),
                            ("active", "Active (6-7 days/week)"),
                            ("very_active", "Very Active (2x/day)"),
                        ],
                        default="moderate",
                        help_text="Physical activity level",
                        max_length=20,
                    ),
                ),
                (
                    "health_goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Lose Weight"),
                            ("weight_gain", "Gain Weight"),
                            ("maintain", "Maintain Weight"),
                            ("muscle_gain", "Build Muscle"),
                            ("general_health", "General Health"),
                        ],
                        default="maintain",
                        help_text="Primary health goal",
                        max_length=20,
                    ),
                ),
                (
                    "daily_calorie_goal",
                    models.IntegerField(
                        blank=True,
                        help_text="Daily calorie target (calculated from TDEE)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1200),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "bmi",
                    models.FloatField(
                        blank=True, help_text="Body Mass Index (calculated)", null=True
                    ),
                ),
                (
                    "water_goal_liters",
                    models.FloatField(
                        default=2.0,
                        help_text="Daily water intake goal in liters",
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "is_onboarding_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has completed onboarding wizard",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
