# Generated by Django 4.2.9 on 2025-11-25 09:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "total_calories",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_protein",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_carbs",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_fat",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_fiber",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total_water_liters",
                    models.FloatField(
                        default=0.0,
                        help_text="Water intake in liters",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "calorie_goal",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Log",
                "verbose_name_plural": "Daily Logs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "calories_per_100g",
                    models.FloatField(
                        help_text="Calories per 100 grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "protein_per_100g",
                    models.FloatField(
                        default=0.0,
                        help_text="Protein per 100 grams in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "carbs_per_100g",
                    models.FloatField(
                        default=0.0,
                        help_text="Carbohydrates per 100 grams in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "fat_per_100g",
                    models.FloatField(
                        default=0.0,
                        help_text="Fat per 100 grams in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "fiber_per_100g",
                    models.FloatField(
                        default=0.0,
                        help_text="Fiber per 100 grams in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "serving_size",
                    models.CharField(
                        default="100g",
                        help_text="Standard serving size description",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this food item has been verified by admin",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
            ],
            options={
                "verbose_name": "Meal Type",
                "verbose_name_plural": "Meal Types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CaloriePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_description",
                    models.TextField(
                        help_text="User's food description or image analysis"
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(
                        blank=True,
                        help_text="Optional uploaded image",
                        null=True,
                        upload_to="prediction_images/%Y/%m/%d/",
                    ),
                ),
                ("predicted_food_name", models.CharField(max_length=200)),
                (
                    "predicted_calories",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "predicted_protein",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "predicted_carbs",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "predicted_fat",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "predicted_quantity",
                    models.FloatField(
                        default=100.0,
                        help_text="Predicted quantity in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(default="google-genai", max_length=50),
                ),
                (
                    "was_saved_to_log",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user saved this prediction to their food log",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calorie Prediction",
                "verbose_name_plural": "Calorie Predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Quantity in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this entry was created from AI prediction",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        help_text="Optional food image",
                        null=True,
                        upload_to="food_images/%Y/%m/%d/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_entries",
                        to="pycalorie.dailylog",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="pycalorie.food",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="pycalorie.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Entry",
                "verbose_name_plural": "Food Entries",
                "ordering": ["-date", "-time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="pycalorie_f_user_id_9c8d62_idx"
                    ),
                    models.Index(
                        fields=["daily_log"], name="pycalorie_f_daily_l_13d7a6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["name", "is_verified"], name="pycalorie_f_name_b0c481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["user", "-date"], name="pycalorie_d_user_id_838407_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="calorieprediction",
            index=models.Index(
                fields=["user", "-created_at"], name="pycalorie_c_user_id_394964_idx"
            ),
        ),
    ]
