# Generated by Django 4.2.9 on 2025-11-25 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pycalorie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="calories",
            field=models.FloatField(
                default=0.0,
                help_text="Total calories for this entry",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="carbs",
            field=models.FloatField(
                default=0.0,
                help_text="Carbs in grams",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="fat",
            field=models.FloatField(
                default=0.0,
                help_text="Fat in grams",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="fiber",
            field=models.FloatField(
                default=0.0,
                help_text="Fiber in grams",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="food_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Name of the food (required for direct entry)",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foodentry",
            name="protein",
            field=models.FloatField(
                default=0.0,
                help_text="Protein in grams",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="food",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to Food database (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="pycalorie.food",
            ),
        ),
        migrations.CreateModel(
            name="FoodImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Food image uploaded by user or AI",
                        upload_to="food_images/%Y/%m/%d/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail for gallery view",
                        null=True,
                        upload_to="food_thumbnails/%Y/%m/%d/",
                    ),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ai_detected_items",
                    models.JSONField(
                        blank=True,
                        help_text="List of detected food items from AI",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_entry",
                    models.OneToOneField(
                        help_text="Associated food entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_image",
                        to="pycalorie.foodentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Image",
                "verbose_name_plural": "Food Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
